package com.example.hotelbookingmanagement.util;

import com.example.hotelbookingmanagement.model.dto.BookingDto;
import com.example.hotelbookingmanagement.model.entity.Booking;

public class EmailTemplateUtil {
    public static String buildWelcomeEmail(String name, String hotelName) {
        return "<!DOCTYPE html>"
                + "<html>"
                + "<head>"
                + "<style>"
                + "body { font-family: 'Arial', sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }"
                + ".container { max-width: 600px; margin: 20px auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }"
                + ".header { background-color: #4A5568; padding: 40px; text-align: center; color: white; }"
                + ".header h1 { margin: 0; font-size: 28px; font-family: 'Playfair Display', serif; }"
                + ".content { padding: 40px; color: #333333; line-height: 1.6; }"
                + ".content p { margin: 0 0 20px; }"
                + ".button { display: inline-block; background-color: #4F46E5; color: #ffffff !important; padding: 12px 25px; border-radius: 5px; text-decoration: none; font-weight: bold; }"
                + ".footer { background-color: #EDF2F7; padding: 20px; text-align: center; font-size: 12px; color: #718096; }"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div class='container'>"
                + "<div class='header'>"
                + "<h1>Welcome to " + hotelName + "</h1>"
                + "</div>"
                + "<div class='content'>"
                + "<h3>Hi " + name + ",</h3>"
                + "<p>Thank you for creating an account with us. We are thrilled to have you as part of our community.</p>"
                + "<p>You can now explore our rooms, book your stay, and manage your reservations all in one place.</p>"
                + "<p><a href='http://localhost:8080/rooms' class='button'>Explore Our Rooms</a></p>"
                + "<p>We look forward to welcoming you soon!</p>"
                + "<p>Best regards,<br>The " + hotelName + " Team</p>"
                + "</div>"
                + "<div class='footer'>"
                + "<p>&copy; 2025 " + hotelName + ". All rights reserved.</p>"
                + "</div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }

    public static String buildBookingSuccessEmail(String name, BookingDto bookingDetails, String hotelName) {
        return "<!DOCTYPE html>"
                + "<html>"
                + "<head>"
                + "<style>"
                // CSS styles remain the same as buildWelcomeEmail
                + "body { font-family: 'Arial', sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }"
                + ".container { max-width: 600px; margin: 20px auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }"
                + ".header { background-color: #4A5568; padding: 40px; text-align: center; color: white; }"
                + ".header h1 { margin: 0; font-size: 28px; font-family: 'Playfair Display', serif; }"
                + ".content { padding: 40px; color: #333333; line-height: 1.6; }"
                + ".content p { margin: 0 0 20px; }"
                + ".footer { background-color: #EDF2F7; padding: 20px; text-align: center; font-size: 12px; color: #718096; }"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div class='container'>"
                + "<div class='header'>"
                + "<h1>Booking Received</h1>"
                + "</div>"
                + "<div class='content'>"
                + "<h3>Dear " + name + ",</h3>"
                + "<p>We have received your booking request. Your reservation is currently pending confirmation from our team. We will notify you again once it's confirmed.</p>"
                + "<p>Your tracking ID is: <strong>" + bookingDetails.getTrackingId() + "</strong></p>"
                + "<p>Thank you for choosing us!</p>"
                + "<p>Best regards,<br>The " + hotelName + " Team</p>"
                + "</div>"
                + "<div class='footer'>"
                + "<p>&copy; 2025 " + hotelName + ". All rights reserved.</p>"
                + "</div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }

    public static String buildBookingConfirmationEmail(String name, BookingDto bookingDetails, String hotelName) {
        return "<!DOCTYPE html>"
                + "<html>"
                + "<head>"
                + "<style>"
                // CSS styles remain the same as buildWelcomeEmail
                + "body { font-family: 'Arial', sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }"
                + ".container { max-width: 600px; margin: 20px auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }"
                + ".header { background-color: #2C5282; padding: 40px; text-align: center; color: white; }"
                + ".header h1 { margin: 0; font-size: 28px; font-family: 'Playfair Display', serif; }"
                + ".content { padding: 40px; color: #333333; line-height: 1.6; }"
                + ".content p { margin: 0 0 20px; }"
                + ".booking-details { border-left: 4px solid #4F46E5; padding-left: 15px; margin: 20px 0; }"
                + ".footer { background-color: #EDF2F7; padding: 20px; text-align: center; font-size: 12px; color: #718096; }"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div class='container'>"
                + "<div class='header'>"
                + "<h1>Booking Confirmed!</h1>"
                + "</div>"
                + "<div class='content'>"
                + "<h3>Dear " + name + ",</h3>"
                + "<p>Great news! Your booking at " + hotelName + " has been confirmed. We are excited to welcome you.</p>"
                + "<div class='booking-details'>"
                + "<p><strong>Tracking ID:</strong> " + bookingDetails.getTrackingId() + "</p>"
                + "<p><strong>Check-in:</strong> " + bookingDetails.getCheckInDate() + "</p>"
                + "<p><strong>Check-out:</strong> " + bookingDetails.getCheckOutDate() + "</p>"
                + "</div>"
                + "<p>If you have any questions, feel free to contact us.</p>"
                + "<p>Best regards,<br>The " + hotelName + " Team</p>"
                + "</div>"
                + "<div class='footer'>"
                + "<p>&copy; 2025 " + hotelName + ". All rights reserved.</p>"
                + "</div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }
    public static String buildBookingCancellationEmail(Booking booking) {
        return "<!DOCTYPE html>"
                + "<html>"
                // ... styles ...
                + "<body>"
                + "<div class='container'>"
                + "<div class='header'><h1>Booking Cancelled</h1></div>"
                + "<div class='content'>"
                + "<h3>Dear " + booking.getGuest().getName() + ",</h3>"
                + "<p>Your booking with Tracking ID: <b>" + booking.getTrackingId() + "</b> has been successfully cancelled.</p>"
                + "<p>If you did not request this cancellation, please contact us immediately.</p>"
                + "</div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }
}
